name: messenger
description: A messaging application for mobile and desktop.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0 < 3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  cupertino_icons:
  intl:
  firebase_core:
  firebase_auth:
  firebase_storage:
  cloud_firestore:
  get_it:
  clock:
  uuid:
  freezed_annotation:
  json_annotation: ^4.3.0
  provider:
  gap:

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints:
  arb_generator:
  build_runner:
  freezed:
  json_serializable:
  fake_cloud_firestore:
  mocktail:
  flutter_test_ui:

flutter:
  uses-material-design: true
  generate: true

arb_generator:
  input_filepath: "assets_dev/loca/loca.csv"
  output_directory: "assets_dev/l10n"
  filename_prepend: "l10n_"
  csv_settings:
    delimiter: ";"
    description_index: 1
    base_index: 2
